spring:
  #  datasource:
  #    url: jdbc:h2:mem:reservation
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  #  h2:
  #    console:
  #      enabled: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mariadb://localhost/reservation?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1q2w3e!Q@W#E
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jwt:
    secret: emItc3ByaW5nLWJvb3QtcmVzZXJ2YXRpb24tcHJvamVjdC1qd3Qtc2VjcmV0LWtleQo=

options:
  maxAllowReserveTime: 10
  maxAllowCancelReservationTime: 10
  allowCheckInTime: 10